#!/bin/sh

# get owner package for file

echo "Run $0 script on `distr_vendor`"
DISTRNAME=`/usr/bin/distr_vendor -d`

[ -n "$1" ] || { echo "Error: Run with dir as param" ; exit 1 ; }

[ "$DISTRNAME" = "ALTLinux" ] && exit 1

cd /tmp

case $DISTRNAME in
	"ALTLinux"|"PCLinux")
		CMD="apt-get --simulate install"
		;;
	"Ubuntu"|"Debian")
		CMD="apt-get --simulate install"
		;;
	"LinuxXP"|"Fedora"|"ASPLinux"|"CentOS"|"RHEL"|"Scientific")
		CMD="yum provides"
		;;
	"Mandriva")
		CMD="urpmi --test --auto"
		;;
	"SUSE")
		CMD="zypper install --dry-run"
		;;
	*)
 		echo "Do not known install command for DISTRNAME $DISTRNAME"
 		exit 2
		;;
esac

$CMD $@
