#!/bin/sh

echo "Run script on `distr_vendor`"
DISTRNAME=`/usr/bin/distr_vendor -d`

# TODO: (not checked yet)
/etc/init.d/etercifs testbuild
exit 0
KVLIST=$( cd /lib/modules && find -L -maxdepth 1 -mindepth 1 -type d | sed -e "s|^./||" )
for i in $KVLIST ; do
	KERNELVERSION=$i /etc/init.d/etercifs build
done
