#!/bin/sh

echo "Run script on `distr_vendor`"
DISTRVENDOR=`/usr/bin/distr_vendor -d`

KVLIST=$( cd /lib/modules && find -L -maxdepth 1 -mindepth 1 -type d | sed -e "s|^./||" )
for i in $KVLIST ; do
	KERNELVERSION=$i /etc/init.d/etercifs build
done
