#!/bin/sh

# install package

[ -n "$1" ] || { echo "Error: Run with package name as param" ; exit 1 ; }

echo "Run install $@ script on `distr_vendor`"
DISTRNAME=`/usr/bin/distr_vendor -d`

[ "$DISTRNAME" = "ALTLinux" ] && exit 1

cd /tmp

case $DISTRNAME in
	"ALTLinux"|"Ubuntu"|"Debian"|"PCLinux")
		[ -n "$INAC" ] && CMD="apt-get install" || CMD="apt-get -y --force-yes install"
		;;
	"LinuxXP"|"Fedora"|"ASPLinux"|"CentOS"|"RHEL"|"Scientific")
		[ -n "$INAC" ] && CMD="yum install" || CMD="yum -y install"
		;;
	"Mandriva")
		[ -n "$INAC" ] && CMD="urpmi --no-verify-rpm" || CMD="urpmi --auto --no-verify-rpm"
		;;
	"SUSE")
		[ -n "$INAC" ] && CMD="zypper --non-interactive install" || CMD="zypper --non-interactive install"
		;;
	*)
		RET=1
		CMD="echo \"Do not known install command for DISTRNAME $DISTRNAME\""
		;;
esac

echo "\$ $CMD $@"
$CMD $@
