#!/bin/sh

echo "Run script on `distr_vendor`"
DISTRNAME=`/usr/bin/distr_vendor -d`
case $DISTRNAME in
	"Ubuntu"|"Debian")
		CMD="dpkg -l | grep -i openoffice"
		;;
	"ALTLinux"|"PCLinux")
		CMD="rpm -qa | grep -i openoffice"
		;;
	"LinuxXP"|"Fedora"|"ASPLinux"|"CentOS"|"RHEL"|"Scientific")
		CMD="rpm -qa | grep -i openoffice"
		;;
	"Mandriva")
		CMD="rpm -qa | grep -i openoffice"
		;;
	"SUSE"|"NLD")
		CMD="rpm -qa | grep -i openoffice"
		;;
	*)
		echo "Skipping unknown DISTRNAME $DISTRNAME"
		;;
esac

$CMD
