#!/bin/sh

# Create urandom device

echo "Run script on `distr_vendor`"
DISTRNAME=`/usr/bin/distr_vendor -d`

[ "$DISTRNAME" = "ALTLinux" ] && exit 1

mknod /dev/random c 1 8
mknod /dev/urandom c 1 9
