#!/bin/sh

# remove package

[ -n "$1" ] || { echo "Error: Run with package name as param" ; exit 1 ; }

echo "Run remove $@ script on `distr_vendor`"
DISTRVENDOR=`/usr/bin/distr_vendor -d`

[ "$DISTVENDOR" = "ALTLinux" ] && exit 1

cd /tmp

case $DISTRVENDOR in
	"Ubuntu"|"Debian")
		CMD="dpkg -P"
		;;
	"ALTLinux"|"LinuxXP"|"Fedora"|"ASPLinux"|"CentOS"|"RHEL"|"Scientific"|"PCLinux"|"Mandriva"|"SUSE")
		CMD="rpm -e"
		;;
	*)
		RET=1
		CMD="echo \"Do not known install command for DISTRVENDOR $DISTRVENDOR\""
		;;
esac

echo "\$ $CMD $@"
$CMD $@
