#!/bin/sh

# remove package

[ -n "$1" ] || { echo "Error: Run with package name as param" ; exit 1 ; }

echo "Run remove $@ script on `distr_vendor`"
DISTRNAME=`/usr/bin/distr_vendor -d`

[ "$DISTRNAME" = "ALTLinux" ] && exit 1

cd /tmp

case $DISTRNAME in
	"Ubuntu"|"Debian")
		CMD="dpkg -P"
		;;
	"ALTLinux"|"LinuxXP"|"Fedora"|"ASPLinux"|"CentOS"|"RHEL"|"Scientific"|"PCLinux"|"Mandriva"|"SUSE")
		CMD="rpm -e"
		;;
	"ArchLinux")
		CMD="pacman -R"
		;;
	"MOPSLinux")
		CMD="mpkg remove"
		;;
	"Gentoo")
		CMD="emerge --unmerge"
		;;
	*)
		RET=1
		CMD="echo \"Do not known install command for DISTRNAME $DISTRNAME\""
		;;
esac

echo "\$ $CMD $@"
$CMD $@
