#!/bin/sh

# remove package

[ -n "$1" ] || { echo "Error: Run with package name as param" ; exit 1 ; }

echo "Run remove $@ script on `distr_vendor`"
DISTRNAME=`/usr/bin/distr_vendor -d`

[ "$DISTRNAME" = "ALTLinux" ] && exit 1

cd /tmp

case $DISTRNAME in
	"ALTLinux"|"Ubuntu"|"Debian"|"PCLinux")
		CMD="apt-get -y --force-yes remove"
		;;
	"LinuxXP"|"Fedora"|"ASPLinux"|"CentOS"|"RHEL"|"Scientific")
		CMD="yum -y remove"
		;;
	"Mandriva")
		CMD="urpme --auto"
		;;
	"SUSE")
		CMD="zypper --non-interactive remove"
		;;
	*)
		RET=1
		CMD="echo \"Do not known install command for DISTRNAME $DISTRNAME\""
		;;
esac

echo "\$ $CMD $@"
$CMD $@
