#!/bin/sh

# install package

[ -n "$1" ] || { echo "Error: Run with package name as param" ; exit 1 ; }

echo "Run install $1 script on `distr_vendor`"
DISTRVENDOR=`/usr/bin/distr_vendor -d`

[ "$DISTVENDOR" = "ALTLinux" ] && exit 1

cd /tmp

case $DISTRVENDOR in
	"ALTLinux"|"Ubuntu"|"Debian"|"PCLinux")
		CMD="apt-cache search"
		;;
	"LinuxXP"|"Fedora"|"ASPLinux"|"CentOS"|"RHEL"|"Scientific")
		CMD="yum search"
		;;
	"Mandriva")
		CMD="urpmf"
		;;
	"SUSE")
		CMD="zypper search"
		;;
	*)
		RET=1
		CMD="echo \"Do not known install command for DISTRVENDOR $DISTRVENDOR\""
		;;
esac

$CMD $1
