#!/bin/sh

# Dummy script

echo "Run $0 script on `distr_vendor`"
DISTRNAME=`/usr/bin/distr_vendor -d`

check_dir()
{
	test -d "$1" || echo "Dir $1 is missed in $DISTRNAME"
}

check_dir /etc/sysconfig
