#!/bin/sh

echo "Run update script on `distr_vendor`"
DISTRNAME=`/usr/bin/distr_vendor -d`

[ "$DISTRNAME" = "ALTLinux" ] && exit 1

cd /tmp

case $DISTRNAME in
	"ALTLinux"|"Ubuntu"|"Debian"|"PCLinux")
		CMDU="apt-get update"
		CMDF="apt-get -f install"
		;;
# skip, will do it automagically
#	"LinuxXP"|"Fedora"|"ASPLinux"|"CentOS"|"RHEL"|"Scientific")
#		CMD="yum update"
#		;;
#	"Mandriva")
#		CMD="urpmf"
#		;;

# skip, will do it automagically
#	"SUSE")
#		CMD="zypper update"
#		;;
	*)
		RET=1
		CMDU="echo \"Do not known install command for DISTRNAME $DISTRNAME\""
		CMDF="false"
		;;
esac

$CMDU && $CMDF
