#!/bin/sh

echo "Run update script on `distr_vendor`"
DISTRNAME=`/usr/bin/distr_vendor -d`

cd /tmp

case $DISTRNAME in
	"ALTLinux")
		exit 0
		;;
	"Ubuntu"|"Debian"|"PCLinux")
		apt-get update || exit
		apt-get -f install || exit
		apt-get autoremove
		;;
# skip, will do it automagically
#	"LinuxXP"|"Fedora"|"ASPLinux"|"CentOS"|"RHEL"|"Scientific")
#		CMD="yum update"
#		;;
#	"Mandriva")
#		CMD="urpmf"
#		;;

# skip, will do it automagically
#	"SUSE")
#		CMD="zypper update"
#		;;
	*)
		RET=1
		echo \"Do not known install command for DISTRNAME $DISTRNAME\"
		exit 1
		;;
esac
