#!/bin/sh
##
#  Korinf project
#
#  Copying functions
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2005-2009
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2009
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

gen_base_apt_rpm()
{
	assert_var DESTDIR TARGETPATH dist
	local SUBDIR=$1
	[ -d "$DESTDIR$SUBDIR" ] || return 1
	if [ ! -d "$DESTDIR$SUBDIR/RPMS.main" ] ; then
		ln -s ./ $DESTDIR$SUBDIR/RPMS.main
	fi
	genbasedir --create --progress --topdir=$TARGETPATH $dist$SUBDIR main
	#chmod o+r $DIR/* -R
# FIXME: need to set ftp/http URL
	cat <<EOF > $DESTDIR$SUBDIR/base/README.korinf.txt
You can add this repo to APT sources.list:
rpm file:$TARGETPATH$SUBDIR $dist main
EOF
}
