#!/bin/sh
##
#  Korinf project
#
#  Check package integrity
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2005-2009
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2009
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

check_pkg_integrity()
{
	epm integrity $@
}

check_files_integrity()
{
	local DIR="$1" EXT
	for EXT in deb rpm tgz tar.gz tar.bz2 tbz zip ; do
		for i in $(find "$DIR" -maxdepth 1 -name "*.$EXT") ; do
			check_pkg_integrity $i && echo "Package $i is OK" || echo "Package $i is broken"
		done
	done
}
