#!/bin/sh
##
#  Korinf project
#
#  Check built packages
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2005-2009
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2009
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

# check package existing by REBUILDLIST
check_built_package()
{
	local NAME FILEDATE FILESIZE BASENAME FILENAME
	local PATHTO=$TARGETPATH CHECKFILE=$1 PATHPKG
	if [ ! -d "$PATHTO" ] ; then
		echo "Path '$PATHTO' is missed"
		return 1
	fi

	for i in $(get_distro_list $REBUILDLIST) ; do
		NAME=$i

		if [ -n "$MAINFILESLIST" ] ; then
			PATHPKG=$PATHTO/$i
		else
			PATHPKG=$PATHTO/$i/extra
		fi

		test -L $PATHPKG && NAME="$NAME [L]"
		FILENAME=$(ls -1 $PATHPKG/${CHECKFILE}* 2>/dev/null | sort -n | head -n1)
		#echo $FILENAME
		if [ -r "$FILENAME" ] ; then
			FILEDATE=`stat -c"%y" $FILENAME | sed -e "s|\..*$||"`
			FILESIZE=`stat -c"%s" $FILENAME`
			BASENAME=`basename $FILENAME`
		else
			if [ -d "$PATHPKG/" ] ; then
				FILEDATE="MISSED"
			else
				FILEDATE="MISDIR"
			fi
			FILESIZE=""
			BASENAME=$NAME
		fi

		printf "%22s: %20s  %7s  %s" "$NAME" "$FILEDATE" "$FILESIZE" "$BASENAME"
		test -L $PATHPKG && echo -n " (link to `readlink $PATHPKG`)"
		echo
	done
}

