#!/bin/sh
##
#  Korinf project
#
#  Check for package requires is present in distro
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2012
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2012
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

load_mod rpm

try_install_by_list()
{
	local dist=$1
	shift
	cd ../tools/run-script
	./run-script.sh $dist checkreqs "$@"
	local RES=$?
	cd -
	return $RES
}

# FIXME: move to common funcs
# args: dir mask
expand_mask_in_dir()
{
	local tdir=$1
	shift
	local i
	for i in $@ ; do
		echo $tdir/$i
	done
}

# args: dist file reqs
print_check_reqs_item()
{
	local dist=$1
	local fname=$(basename $2)
	shift 2
	local reqs=$@

	if [ "$CHECKREQUIRES" = "-R" ] ; then
		printf "* %s: %s" "$fname" "$(echo $reqs)"
		[ -z "$reqs" ] && echo "EMPTY" && continue
		echo
		try_install_by_list $dist "$reqs" && echo "  OK" || echo "FAIL"
	else
		printf "  * %60s: " "$fname"
		[ -z "$reqs" ] && echo "Empty list" && continue
		try_install_by_list $dist "$reqs" >/dev/null 2>&1 && echo "  OK" || echo "FAIL"
	fi
}


# check package existing by REBUILDLIST
# used: TARGETPATH REBUILDLIST
check_package_requires()
{
	local BUILDNAME=$1
	local SRCPKG
	local reqs

	if [ ! -d "$TARGETPATH" ] ; then
		echo "Path TARGETPATH:'$TARGETPATH' is missed"
		return 1
	fi

	test -L "$TARGETPATH/$dist" && continue

	echo "Note: we do not use info from built packages, only check if file is exists"
	SRCPKG=$(get_src_package "$SOURCEPATH" $BUILDNAME)
	[ -n "$QUIET" ] || echo "Source package: $SRCPKG"

	for dist in $(get_distro_list $REBUILDLIST) ; do
		# fills $BUILDARCH, $DISTRNAME, $DISTRVERSION
		parse_dist_name $dist
		[ -z "$DISTRNAME" ] && fatal "Empty DISTRNAME for $dist"

		# fills $PKGFORMAT, $PKGVENDOR, $RPMVENDOR
		set_target_var
		prepare_filelist
		[ "$CHECKREQUIRES" = "-R" ] && echo "====================="
		printf "%-20s\n" "$BUILDARCH/$DISTRNAME/$DISTRVERSION"

		# first print about source package
		reqs=$(get_rpmpkg_requires -p $SRCPKG)
		reqs=$(convert_pkgreqs_to_target $reqs)
		print_check_reqs_item $dist $SRCPKG $reqs

		for j in $(expand_mask_in_dir $TARGETPATH/$dist $EXPMAINFILES) $(expand_mask_in_dir $TARGETPATH/$dist/extra $EXPEXTRAFILES) ; do
			[ -r "$j" ] || continue
			pkgname=$(get_pkgname_from_filename $j)
			reqs=$(get_target_deplist $pkgname)
			print_check_reqs_item $dist $j $reqs
		done
	done
}

