#!/bin/sh
# 2005, 2006, 2007, 2009 (c) Etersoft http://etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# GNU Public License version 3

# do not include again
if [ -z "$CHROOTDIR" ] ; then

# Нужно отделить общий конфиг он частного WINE

# We need rw group and permit reading to all
umask 0002

export LANG=C
export LC_ALL=C

# FIXME: User in local system (with the same uid as INTUSER)
LOCUSER=builder

# User in remote(build) system
INTUSER=lav

# Path to chroot dir (remote system mounted)
CHROOTDIR=/tmp/autobuild
# FIXME
mkdir -p $CHROOTDIR

# Linux builder
LINUXHOST=/net/os/stable

# FreeBSD builder
FREEBSDSSH=$LOCUSER@freebsd
[ "$USER" = "lav" ] && FREEBSDKEY="-i /home/lav/.ssh/id_dsa.builder"
FREEBSDPATH=home/$LOCUSER/work-$$

test -z "$WORKDIR" && export WORKDIR=`pwd`

# FIXME
if [ -n "$WORKDIR" ] ; then
	ALOGDIR=$WORKDIR/log
	# Hack for run from package
	if [ ! -w "$ALOGDIR" ] ; then
		ALOGDIR=$TMPDIR/korinf-log
	fi
	# Make log dir with date for builder user only
	[ "$USER" = "builder" ] && ALOGDIR=$ALOGDIR/`date "+%Y%m%d"`
	# убрать надо
	[ "$WORKDIR" = `pwd` ] || mkdir -p $ALOGDIR
	#mkdir -p $CHROOTDIR
fi

# load Korinf config
test -f $KORINFETC/korinf && . $KORINFETC/korinf
test -f ~/.config/korinf  && . ~/.config/korinf

fi
# end if CHROOTDIR
