#!/bin/sh
# 2005, 2006, 2007, 2009 (c) Etersoft http://etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# GNU Public License version 3

# do not include again
if [ -z "$CHROOTDIR" ] ; then

# Нужно отделить общий конфиг он частного WINE

# We need rw group and permit reading to all
umask 0002

export LANG=C

export PRODUCTNAME="WINE@Etersoft"

# Каталог с деревом пакетов свободного WINE и файлов к нему
export WINEPUB_PATH=/var/ftp/pub/Etersoft/$PRODUCTNAME

# Каталог с закрытой частью
export WINEETER_PATH=/var/ftp/pvt/Etersoft/$PRODUCTNAME

# FIXME: User in local system (with the same uid as INTUSER)
export LOCUSER=builder

# User in remote(build) system
export INTUSER=lav

# Path to chroot dir (remote system mounted)
export CHROOTDIR=/tmp/autobuild
mkdir -p $CHROOTDIR

# Path for mount tasks
export TASKDIR=$HOME/sales

# Linux builder
export LINUXHOST=/net/os/stable

# FreeBSD builder
export FREEBSDSSH=$LOCUSER@freebsd
[ "$USER" = "lav" ] && export FREEBSDKEY="-i /home/lav/.ssh/id_dsa.builder"
export FREEBSDPATH=home/$LOCUSER/work-$$

# Менять можно: версия, которая идёт на сборку заказов, устанавливается в arobot.sh!
if [ -z "$WINENUMVERSION" ] ; then
	export WINENUMVERSION="1.0.9"
fi

test -z "$WORKDIR" && export WORKDIR=`pwd`

# FIXME
if [ -n "$WORKDIR" ] ; then
	ALOGDIR=$WORKDIR/log
	# Hack for run from package
	if [ ! -w "$ALOGDIR" ] ; then
		ALOGDIR=$TMPDIR/korinf-log
	fi
	# Make log dir with date for builder user only
	[ "$USER" = "builder" ] && ALOGDIR=$ALOGDIR/`date "+%Y%m%d"`
	export ALOGDIR
	# убрать надо
	[ "$WORKDIR" = `pwd` ] || mkdir -p $ALOGDIR
	#mkdir -p $CHROOTDIR
fi

fi

# load Korinf config
test -f /etc/eterbuild/korinf && . /etc/eterbuild/korinf
test -f ~/.config/korinf  && . ~/.config/korinf
# end if CHROOTDIR
