#!/bin/sh
# 2005, 2006, 2007, 2009 (c) Etersoft http://etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# GNU Public License version 3

# do not execute again
if [ -z "$CHROOTDIR" ] ; then

# Нужно отделить общий конфиг он частного WINE

# We need rw group and permit reading to all
umask 0002

export LANG=C
export LC_ALL=C

# FIXME: User in local system (with the same uid as INTUSER)
LOCUSER=builder

# Path to built packages inside home
RPMSDIR=RPM/RPMS

# Path to chroot dir (remote system mounted)
CHROOTDIR=/tmp/autobuild
# FIXME
mkdir -p $CHROOTDIR

# load Korinf config
test -f /etc/eterbuild/korinf && . /etc/eterbuild/korinf
test -f $KORINFETC/korinf && . $KORINFETC/korinf
test -f ~/.config/korinf  && . ~/.config/korinf

[ -n "$EMAILNOTIFY" ] || EMAILNOTIFY=$USER

RPMBPH=$ETERBUILDBIN/rpmbph
RPMBSH=$ETERBUILDBIN/rpmbsh
RPMBS=$ETERBUILDBIN/rpmbs

# HACK: create strip workaround
create_strip_workaround()
{
	# FIXME: run this script inside chroot? under korinfer user
	mkdir -p $BUILDERHOME/bin-korinf
	chgrp builder $BUILDERHOME/bin-korinf || { warning "Not in builder group" ; return 1; }
	chmod ug+rwX $BUILDERHOME/bin-korinf

	cat >$BUILDERHOME/bin-korinf/strip <<EOF
# Skip hasplmd due broken strip
if echo "\$@" | grep hasplmd >/dev/null ; then
	true
else
	/usr/bin/strip \$@
fi
EOF
	chmod a+x $BUILDERHOME/bin-korinf/strip
	$SUDO chown $LOCUSER $BUILDERHOME/bin-korinf/strip
}


# Create need for build files in home dir
init_home()
{
	if [ ! -d $BUILDERHOME/ ] ; then
		return
	fi

	# FIXME: ebconfig is obsolete
	[ -r $BUILDERHOME/.ebconfig ] || echo "RPMBUILD=rpmbuild" > $BUILDERHOME/.ebconfig

	#create_strip_workaround

	# create rpmmacros if missed
	if [ -r $BUILDERHOME/.rpmmacros ] ; then
		return
	fi

cat <<EOF >$BUILDERHOME/.rpmmacros || fatal "Can't copy macros"
# Etersoft's default macros
%_topdir        /home/$INTUSER/RPM
%_tmppath       /home/$INTUSER/tmp
%_sourcedir %_topdir/SOURCES
%vendor Etersoft
%distribution WINE@Etersoft
#%_target_cpu i586
%buildhost builder.etersoft.ru
# do wrong (crossed with --buildroot?
#%BuildRoot: %_tmppath/%{name}-%{version}
#%buildroot: %_tmppath/%{name}-%{version}
%packager Etersoft Builder <support@etersoft.ru>

# see http://wiki.sisyphus.ru/devel/RpmSetup
%_build_name_fmt %{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}.rpm
EOF

}

fi
# end if CHROOTDIR
