#!/bin/sh
# 2005, 2006, 2007, 2008, 2009 (c) Etersoft http://etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# GNU Public License version 3
#
# Main script for build packages

# Example in three lines:
#  kormod helpers
#  export REBUILDLIST=lists/rebuild.list.all
#  build_build your-package-name

kormod main

# build binary packages according to REBUILDLIST
# arg: package_name [HELPER]
build_rpm()
{
	# FIXME: for compatibility
	set_log_dir

	echo
	echo " =============================================== "
	echo | write_report

	local BUILDNAME
	test -n "$1" && BUILDNAME=$1 || fatal "Missed build_rpm param"

	# disable changelog editing
	export EDITOR=

	MAINFILESLIST=$MAINFILES
	EXTRAFILESLIST=$EXTRAFILES

	# Use default value for simple backward compatibility
	if [ -z "$MAINFILESLIST$EXTRAFILESLIST" ] ; then
		if [ "$2" = "HELPER" ] ; then
			EXTRAFILESLIST="${BUILDNAME}"
		else
			MAINFILESLIST="${BUILDNAME}"
		fi
	fi

	echo "SOURCE=$SOURCEPATH TARGET=$TARGETPATH"

	if [ -z "$SOURCEPATH" ] || [ -z "$TARGETPATH" ] ; then
		fatal "Source or target path is not set"
	fi

	main_build
}

# build source packages according to REBUILDLIST
# args: package_name
build_srpm()
{
	MAKESPKG=1
	build_rpm $@
}

