#!/bin/sh
##
#  Korinf project
#
#  After build install functions
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2005-2009
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2009
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##


# install built packages
install_built()
{	
	local NODEPS
	echo "Install built $TARGET packages to $BUILDROOT root dir..."
	# Do not install debug packages
	#rm -f $BUILTRPM/*debug*
	#BUILDFILES=`echo *${BUILDNAME}*$TARGET`	
	#popd
	# Note: немного странно с кавычками и разворачиванием звёздочек
	case $TARGET in
		"deb") # Debian/Ubuntu
			$SUDO chroot $BUILDROOT su - -c "$NICE dpkg -i --force-all $INTBUILT/*${BUILDNAME}*.$TARGET"
			#$SUDO chroot $BUILD $NICE dpkg -i --force-overwrite "$INTBUILT/*${BUILDNAME}*.$TARGET"
			RES=$?
			;;
		"tgz") # Slackware
			$SUDO chroot $BUILDROOT $NICE installpkg "$INTBUILT/*${BUILDNAME}*.$TARGET"
			RES=$?
			;;
		"tar.gz") # Hack for ArchLinux
			$SUDO chroot $BUILDROOT su - -c "$NICE pacman -U --force --nodeps /home/$INTUSER/abs/$PACKAGE/*${BUILDNAME}*.pkg.$TARGET"
			#$SUDO chroot $BUILDROOT su - -c "cd / ; ls -1 $INTBUILT/*${BUILDNAME}*.$TARGET | xargs -n1 --no-run-if-empty $NICE tar xfvz "
			RES=$?
			;;
		*)
			# First time install without dependences
			# DURING_INSTALL for disable start_service
			[ -n "$WITHOUTEBU" ] && NODEPS=--nodeps
			$SUDO chroot $BUILDROOT su - -c "cd $INTBUILT && DURING_INSTALL=1 $NICE rpm -Uvh ${EXPMAINFILES} ${EXPEXTRAFILES} --force $NODEPS"
			RES=$?
			#[ "$RES" = "0" ] || warning "install status: failed"
			# Hack: broken return status on some systems
			#RES=0
			;;
	esac
	return $RES
}

# install required packages for build
install_req()
{
	# TODO
	echo
}
