#!/bin/bash
##
#  Korinf project
#
#  Main build cycle functions
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2005, 2006, 2007, 2009
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2009
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

kormod mount copying install log
kormod distro


exit_handler()
{
    local rc=$?
    trap - EXIT
    warning "Interrupted, exiting..."
    end_umount
    exit $rc
}

main_build()
{

trap exit_handler EXIT HUP INT QUIT PIPE TERM

[ -n "$ADEBUG" ] && echo "BUILDNAME: $BUILDNAME"

# HACK: Url for remote building
SOURCEURL=$(echo $SOURCEPATH | sed -e "s|/var/ftp/|ftp://server/|g")

# On systems with portage change wine package name
# FIXME: set PACKAGE individually
[ "$BUILDNAME" = "wine" ] && PACKAGE="wine-etersoft-public" || PACKAGE=$BUILDNAME

BUILDSRPM=$(get_src_package "$SOURCEPATH" $BUILDNAME || fatal "Can't find package for $BUILDNAME")

PACKAGEVERSION=$(rpm -qp "$BUILDSRPM" --queryformat="%{VERSION}")
[ -n "$PACKAGEVERSION" ] || fatal "Can't get version from $BUILDSRPM package"

rpm --checksig $BUILDSRPM || warning "GPG check failed"

# disable gear using due pre hasher repacking problem
export IGNOREGEAR=1

CMDRE=$(get_distro_list $REBUILDLIST)
[ -z "$CMDRE" ] && fatal "build list is empty"

for dist in $CMDRE ; do

	# fill after hasher
	BUILTBINPKGLIST=

	# Set target dir for built packages
	DESTDIR=$TARGETPATH/$dist

	# skip linked destination
	[ -L "$DESTDIR" ] && continue

	# FIXME: Hack
	[ "$TARGETPRIVPATH" ] && DESTDIR=$TARGETPRIVPATH

	dist_ver=`echo $dist | sed -e "s|.*/||g"`
	dist_name=`echo $dist | sed -e "s|/.*||g"`
	[ -z "$dist_name" ] && fatal "Empty dist_name for $dist"

	# Initialize LOGDIR and LOGFILE variables
	init_dist_log "$dist"
	logit "`basename $BUILDSRPM .src.rpm`"

	# Run build and check result
	if build_dist_pkg ; then
		logit "copying log" copying_log || return 1
	else
		# Get error, umount if do not need debug
		if [ -z "$ADEBUG" ] ; then
			logit "umount" end_umount
		fi

		logit "copying log from broken build" copying_log

		# Stop immediately if we in auto build
		if [ -n "$NIGHTBUILD" ] ; then
			echo `date` $dist FATAL | write_report
			fatal "Fatal autobuild"
		fi
	fi

	echo `date` $dist DONE | write_report
done

# disable trap before exit
trap - EXIT
}
