#!/bin/bash
##
#  Korinf project
#
#  Status related functions
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2012
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2012
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

set_build_failed()
{
	set_destlogdir
	touch "$DESTLOGDIR/$BUILDNAME.build.failed" || fatal "Can't set build status"
	return 1
}

set_autobuild_failed()
{
	set_destlogdir
	touch "$DESTLOGDIR/$BUILDNAME.autobuild.failed" || fatal "Can't set autobuild status"
	return 1
}

is_build_failed()
{
	set_destlogdir
	[ -r "$DESTLOGDIR/$BUILDNAME.build.failed" ]
}

is_autobuild_failed()
{
	set_destlogdir
	[ -r "$DESTLOGDIR/$BUILDNAME.autobuild.failed" ]
}

clear_build_status()
{
	set_destlogdir
	rm -fv "$DESTLOGDIR/$BUILDNAME.build.failed"
	rm -fv "$DESTLOGDIR/$BUILDNAME.autobuild.failed"
	return 0
}
