#!/bin/sh -x
##
#  Korinf project
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2006, 2007, 2009, 2013
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2006, 2007, 2009, 2013
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

# sets FTPDIR (dir with license file)
# use: LICENSEFILE
create_license_dir()
{
	assert_var TARGETDIR PROJECTVERSION ETERREGNUM AROBOTDIR LICENSEFILE
	export FTPDIR=$TARGETDIR/$PROJECTVERSION
	# Можем стирать только каталог дистрибутива, а не весь
	test -d $FTPDIR && rm -rf $FTPDIR
	mkdir -p $FTPDIR || fatal "error with $FTPDIR creating"

	echo >> $ALOGDIR/autobuild.report.log
	echo "$(date): Build license $TYPE for $ETERREGNUM in $FTPDIR" >> $ALOGDIR/autobuild.report.log

	# Вывод скрипта не записывается в лог
	export BUILDSTRAP=

	create_license $FTPDIR/$LICENSEFILE $AROBOTDIR/dsa/$(basename $LICENSEFILE .lic).dsa
}


# Ошибка: не ловятся ошибки отсюда
# args: fileto, email
prepare_license_mail()
{
	local FILETO BETA WRITETO
	assert_var PRODUCT PROJECTVERSION TYPE_LICENSE FULLNAME
	assert_var FTPDIR DOWNLOADDIR
	FILETO=$1
	WRITETO=$2
	#LICENSEDIR=$3
	>$FILETO
	NAME="$(get_dear_from_fio "$FULLNAME" "покупатель")"

	if [ "$TYPE_LICENSE" = "Demo" ] || [ "$TYPE_LICENSE" = "DemoTerminal" ] ; then
		THANKTEXT="Благодарим Вас за внимание к нашему продукту."
	else
		THANKTEXT="Благодарим Вас за покупку!"
	fi

	cat >>$FILETO <<EOF
${DEAR} ${NAME}!

Вы заказывали лицензию для Продукта
${PRODUCT} (релиз $PROJECTVERSION)
с регистрационным номером ${ETERREGNUM}.

Файл лицензии можно скачать по следующей ссылке:
EOF
	printURL "$FTPDIR" "$DOWNLOADDIR/$PROJECTVERSION" $LICENSEFILE >>$FILETO || fatal "Error with license (files are missed) "

	cat >>$FILETO <<EOF

Файл лицензии $LICENSEFILE необходимо расположить в каталоге $LICENSEDIR
и проверить права на его чтение пользователями.

По вопросам использования продукта пишите на $WRITETO, указав
в теме письма регистрационный номер.

Пожалуйста, отвечайте на это письмо только
при возникновении затруднений со скачиванием файлов.

$THANKTEXT

-- 
Команда разработчиков
Etersoft, 2017
EOF
}
