#!/bin/sh -x
##
#  Korinf project
#
#  Publish any component for client by task file
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2006, 2007, 2009, 2013
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2006, 2007, 2009, 2013
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

# Выполняет сборку по первому заказу в списке
# Отправляет на реальный адрес только с параметром --real /путь
# Также отладку можно включить, создав файл arobot.sh.debug
# (c) Etersoft
# 08.06.2006, 09.06.06, 28.02.07, 09.03.07, 15.12.07, 2008
# FIXME: если в имени запятая, разделяет на два адреса
#

# Ошибка: не ловятся ошибки отсюда
prepare_component_mail()
{
	local FILETO BETA
	FILETO=$1
	>$FILETO
	NAME="$(get_dear_from_fio "$FULLNAME" "покупатель")"
	BETA=""

	if [ "$TYPE_LICENSE" = "Demo" ] ; then
		THANKTEXT="Благодарим Вас за внимание к нашему продукту."
	else
		THANKTEXT="Благодарим Вас за покупку!"
	fi

	cat >>$FILETO <<EOF
${DEAR} ${NAME}!

Ваш заказ компоненты ${COMPONENTNAME} (версия $PROJECTVERSION)
для продукта ${PRODUCT} выполнен.
${BETA}
Регистрационный номер Продукта: ${ETERREGNUM}.

Вам потребуется скачать файлы по приведённым ссылкам:

EOF
	LOCALFILES=`find -L $LOCALDIR/$DIST -maxdepth 1 -type f`
	printURL "$LOCALDIR/$DIST" "$PUBDOWNLOAD/$DIST" $LOCALFILES >>$FILETO || fatal "Error with ftp ($LOCALDIR with '$LOCALFILES') (possible files are missed!)"

# only if have license file
if [ -f "$FTPDIR/$LICENSEFILE" ] ; then
cat >>$FILETO <<EOF

Файл лицензии можно скачать по следующей ссылке:
EOF
	printURL "$FTPDIR" "$DOWNLOADDIR/$PROJECTVERSION" $LICENSEFILE >>$FILETO || fatal "Error with license (files are missed) "
	cat >>$FILETO <<EOF

Файл лицензии $LICENSEFILE необходимо расположить в каталоге $LICENSEDIR
и проверить права на его чтение пользователями.
EOF
fi

	cat >>$FILETO <<EOF

При необходимости эти же файлы могут быть получены по протоколу $RPROTO: замените $MPROTO:// на $RPROTO:// в пути.
EOF
if echo "$PUBDOWNLOAD" | grep -q "/pub/Etersoft" ; then
	cat >>$FILETO <<EOF
Также Вы можете напрямую зайти в каталог, чтобы загрузить файлы:
	$PUBDOWNLOAD/$DIST
EOF
fi
	cat >>$FILETO <<EOF

Вы можете напрямую зайти в каталог, чтобы загрузить файлы:
	${DOWNLOADDIR}/$PROJECTVERSION/$DIST
EOF

	cat >>$FILETO <<EOF

По вопросам использования продукта пишите на support@etersoft.ru, указав
в теме письма регистрационный номер.

Пожалуйста, отвечайте на это письмо только при возникновении затруднений со скачиванием файлов.

$THANKTEXT

-- 
Команда разработчиков
Etersoft, 2018
EOF
}

# DOWNLOADDIR - RX@Etersoft/VERSION
build_anycomponent()
{
	local COMPONENTSCRIPTDIR
	local CHECKCOMP
	local PROJ=$DOWNLOADDIR
	LOCALDIR=/var/ftp/pub/Etersoft/$PROJ
	
	# Lav 28.06.11: skip checking for previous built one
	#if [ ! -d "$LOCALDIR/$DIST" ] ; then
	#	warning "System $DIST not supported for build ($LOCALDIR/$DIST does not exist)"
	#	do_broken
	#fi

	# Use real path if possible
	# NOTE: replace PROJECTVERSION with linked version
	if [ -L "$LOCALDIR" ] ; then
		LOCALDIR=`readlink -f "$LOCALDIR"`
		PROJECTVERSION=`basename $LOCALDIR`
		PROJ=`dirname $PROJ`/$PROJECTVERSION
	fi
	[ -n "$PROJ" ] || exit
	PUBDOWNLOAD="$MPROTO://$DOWNLOADDOMAIN/pub/Etersoft/$PROJ"
	KORINFLOCAL="/var/ftp/pub/Korinf"

	TEXTDIST=$DIST
	# Check for linked system (собираем для основной системы)
	if [ -L "$LOCALDIR/$DIST" ] ; then
		DIST=`readlink $LOCALDIR/$DIST | sed -e "s|\.\./||g"`
		TEXTDIST="$TEXTDIST (фактически сборка выполнена для $DIST)"
	fi
	
	if [ -z "$LICENSEONLY" ] ; then
		check_dist $DIST
	fi

	# need for license file creating
	local CNAME=$(strip_spaces $COMPONENTNAME)
	# will do FTPDIR from it in create_license_dir
	TARGETDIR="/var/ftp/pub/download/$CNAME/$TARGETDIRNAME"
	DOWNLOADDIR="$MPROTO://$DOWNLOADDOMAIN/pub/download/$CNAME/$TARGETDIRNAME"

	case "$COMPONENTNAME" in
	"RX@Etersoft")
		LOCALDIR=/var/ftp/pvt/Etersoft/$PROJ
		PUBDOWNLOAD=$DOWNLOADDIR/$PROJECTVERSION
		if [ "$PROJECTVERSION" = "1.1.3" ] ; then
			COMPONENTSCRIPTDIR="bin-nx"
			CHECKCOMP="opennx rx-etersoft nx"

			if [ "$DIST" = "Windows/ALL" ] ; then
				CHECKCOMP="opennx"
			fi
		elif [ "$PROJECTVERSION" = "1.1.4" ] ; then
			COMPONENTSCRIPTDIR="bin-rx"
			CHECKCOMP="rxclient rx-etersoft nx"

			if [ "$DIST" = "Windows/ALL" ] ; then
				CHECKCOMP="opennx"
			fi
		else
			COMPONENTSCRIPTDIR="bin-rx"
			CHECKCOMP="rxclient rx-etersoft nx-libs nxssh"

			if [ "$DIST" = "Windows/ALL" ] ; then
				CHECKCOMP="rxclient"
			fi
		fi

		# TODO: nxsadmin

		# exports FTPDIR
		LICENSEFILE=rx-etersoft.lic
		LICENSEDIR="/etc/nxserver"
		create_license_dir

		;;
	"Postgres@Etersoft")
		COMPONENTSCRIPTDIR="bin-postgres"
                if echo "$PROJECTVERSION" | grep -q "8.3" ; then
			CHECKCOMP="postgresql-8.3eter"
		else
			CHECKCOMP="postgresql-8.4eter"
		fi
		# TODO: has not source pkg: postgresql-8.3eter-contrib postgresql-8.3eter-server"
		;;
	"Postgre@Etersoft 9")
		COMPONENTSCRIPTDIR="bin-postgres"
		if echo "$PROJECTVERSION" | grep -q "9.0" ; then
			CHECKCOMP="postgre-etersoft9.0"
		elif echo "$PROJECTVERSION" | grep -q "9.1" ; then
			CHECKCOMP="postgre-etersoft9.1"
		elif echo "$PROJECTVERSION" | grep -q "9.2" ; then
			CHECKCOMP="postgre-etersoft9.2"
		else
			CHECKCOMP="postgre-etersoft9.6"
		fi
		;;
	*)
		COMPONENTSCRIPTDIR="NO"
		CHECKCOMP=""
		echo "No check rule for component '$COMPONENTNAME'"
		;;
	esac

	# Для отправки писем обязательно нужна локаль!
	export LC_ALL=ru_RU.UTF-8
	TMPMAIL=`mktemp`

	if [ -n "$LICENSEONLY" ] ; then
		prepare_license_mail $TMPMAIL support@etersoft.ru || fatal "Can't prepare letter"
	else
		for i in $CHECKCOMP ; do
			check_and_refresh_component $COMPONENTSCRIPTDIR $LOCALDIR $i
			assert_present_package $LOCALDIR/$DIST $i
		done

		check_and_refresh_package $KORINFLOCAL eepm
		PUB6FILES=`find -L $KORINFLOCAL/$DIST -maxdepth 1 -type f -name "eepm*"`

		if echo "$LOCALDIR" | grep -q "/pvt/Etersoft" ; then
			[ -n "$PRIVFILES" ] || PRIVFILES=`find -L $LOCALDIR/$DIST -maxdepth 1 -type f`
			[ -n "$PRIVFILES" ] || fatal "Can't find files in $LOCALDIR/$DIST"
			# Нужно скопировать файлы
			mkdir -p $FTPDIR/$DIST
			for i in $PRIVFILES $PUB6FILES; do
				# try create hard link firstly
				cp -fl $i $FTPDIR/$DIST || cp -f $i $FTPDIR/$DIST || fatal "Can't copy $i"
			done
			# replace LOCALDIR for link list!
			LOCALDIR=$FTPDIR
		fi

		prepare_component_mail $TMPMAIL || fatal "Can't prepare letter"
	fi

	cat $TMPMAIL | mutt "${FULLMAILTO}" -b "sales-track@etersoft.ru" -s "$ETERREGNUM: Сборка $COMPONENTNAME $PROJECTVERSION" || fatal "Can't send"
	rm -f $TMPMAIL
}

