#!/bin/sh -x
##
#  Korinf project
#
#  Publish any component for client by task file
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2006, 2007, 2009
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2006, 2007, 2009
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

# Выполняет сборку по первому заказу в списке
# Отправляет на реальный адрес только с параметром --real /путь
# Также отладку можно включить, создав файл arobot.sh.debug
# (c) Etersoft
# 08.06.2006, 09.06.06, 28.02.07, 09.03.07, 15.12.07, 2008
# FIXME: если в имени запятая, разделяет на два адреса
#


# Ошибка: не ловятся ошибки отсюда
prepare_component_mail()
{
	local FILETO BETA
	FILETO=$1
	>$FILETO
	NAME=`get_name "$FULLNAME"`
	BETA=""

	if [ "$TYPE_LICENSE" = "Demo" ] ; then
		THANKTEXT="Благодарим Вас за внимание к нашему продукту."
	else
		THANKTEXT="Благодарим Вас за покупку!"
	fi

	cat >>$FILETO <<EOF
${DEAR} ${NAME}!

Ваш заказ компоненты ${COMPONENTNAME} (версия $PROJECTVERSION)
для продукта ${PRODUCT} выполнен.
${BETA}
Регистрационный номер Продукта: ${ETERREGNUM}.

Вам потребуется скачать файлы по приведённым ссылкам:

EOF
	LOCALFILES=`find -L $LOCALDIR/$DIST -maxdepth 1 -type f`
	printURL $LOCALDIR/$DIST $FTPDIR/$DIST $LOCALFILES >>$FILETO || fatal "Error with ftp ($LOCALDIR with '$LOCALFILES') (possible files are missed!)"


	cat >>$FILETO <<EOF

При необходимости эти же файлы могут быть получены по протоколу http: замените ftp:// на http:// в пути.
Также Вы можете напрямую зайти в каталог, чтобы загрузить файлы:
	$FTPDIR/$DIST

При возникновении затруднений со скачиванием файлов просим привести
описание проблемы в ответе на данное письмо.

$THANKTEXT

-- 
Команда разработчиков
Etersoft, 2009
EOF
}

build_anycomponent()
{
	#local PROJ="$COMPONENTNAME/$PROJECTVERSION"
	local PROJ=$DOWNLOADDIR
	LOCALDIR=/var/ftp/pub/Etersoft/$PROJ
	
	if [ ! -d "$LOCALDIR/$DIST" ] ; then
		warning "System $DIST not supported for build ($LOCALDIR/$DIST does not exist)"
		do_broken
	fi

	# Use real path if possible
	# NOTE: replace PROJECTVERSION with linked version
	if [ -L "$LOCALDIR" ] ; then
		LOCALDIR=`readlink -f "$LOCALDIR"`
		PROJECTVERSION=`basename $LOCALDIR`
		PROJ=`dirname $PROJ`/$PROJECTVERSION
	fi
	FTPDIR="ftp://updates.etersoft.ru/pub/Etersoft/$PROJ"


	TEXTDIST=$DIST
	# Check for linked system (собираем для основной системы)
	if [ -L "$LOCALDIR/$DIST" ] ; then
		DIST=`readlink $LOCALDIR/$DIST | sed -e "s|\.\./||g"`
		TEXTDIST="$TEXTDIST (фактически сборка выполнена для $DIST)"
	fi
	
	check_dist $DIST

	echo >> $ALOGDIR/autobuild.report.log
	echo "Build $TYPE for $ETERREGNUM in $FTPDIR" >> $ALOGDIR/autobuild.report.log

	case "$COMPONENTNAME" in
	"RX@Etersoft")
		COMPONENTSCRIPT="bin-nx"
		if [ "$BUILDARCH" = "x86_64" ] ; then
			CHECKCOMP="nx freenx-server"
		else
			CHECKCOMP="nx nxclient freenx-server"
		fi
		# TODO: nxsadmin
		;;
	"Postgres@Etersoft")
		COMPONENTSCRIPT="bin-postgres"
		CHECKCOMP="postgresql-8.3eter"
		# TODO: has not source pkg: postgresql-8.3eter-contrib postgresql-8.3eter-server"
		;;
	*)
		COMPONENTSCRIPT="NO"
		CHECKCOMP=""
		echo "No check rule for component '$COMPONENTNAME'"
		;;
	esac

	for i in $CHECKCOMP ; do
		check_and_refresh_component $COMPONENTSCRIPT $LOCALDIR/$DIST $i
		check_package $LOCALDIR/$DIST $i
	done

	#create_license $FTPDIR/selta.lic $AROBOTDIR/dsa/selta.dsa

	# Для отправки писем обязательно нужна локаль!
	export LC_ALL=ru_RU.UTF-8
	TMPMAIL=`mktemp`

	prepare_component_mail $TMPMAIL || fatal "Can't prepare letter"

	cat $TMPMAIL | mutt "${FULLMAILTO}" -b "support@etersoft.ru" -s "Сборка $COMPONENTNAME $PROJECTVERSION" || fatal "Can't send"
	rm -f $TMPMAIL
}

