#!/bin/sh -x
##
#  Korinf project
#
#  Publish SELTA@Etersoft product for client by task file
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2006, 2007, 2009
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2006, 2007, 2009
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

# Выполняет сборку по первому заказу в списке
# Отправляет на реальный адрес только с параметром --real /путь
# Также отладку можно включить, создав файл arobot.sh.debug
# (c) Etersoft
# 08.06.2006, 09.06.06, 28.02.07, 09.03.07, 15.12.07, 2008
# FIXME: если в имени запятая, разделяет на два адреса
#

# Ошибка: не ловятся ошибки отсюда
prepareSeltaMail()
{
	local FILETO BETA
	FILETO=$1
	>$FILETO
	NAME="$(get_dear_from_fio "$FULLNAME" "покупатель")"
	BETA=""

	if [ "$TYPE_LICENSE" = "Demo" ] ; then
		THANKTEXT="Благодарим Вас за внимание к нашему продукту."
	else
		THANKTEXT="Благодарим Вас за покупку!"
	fi

	cat >>$FILETO <<EOF
${DEAR} ${NAME}!

Ваш заказ Продукта ${PRODUCT} (релиз $PROJECTVERSION) выполнен.
${BETA}
Регистрационный номер Продукта: ${ETERREGNUM}.

Для получения Продукта необходимо скачать файлы по приведённым ссылкам:

Установочный пакет SELTA@Etersoft (файл selta.msi) и файл лицензии (selta.lic):
EOF
	LOCALFILES=selta.msi
	printURL $PUBLOCAL $PUBDOWNLOAD1 $LOCALFILES >>$FILETO || fatal "Error with mirror 1 ($PUBLOCAL with '$LOCALFILES') (possible files are missed!)"
	printURL $FTPDIR $DOWNLOADDIR/$PROJECTVERSION `find -L  $FTPDIR -maxdepth 1 -type f ` >>$FILETO || fatal "Error with private part (files are missed) "

	cat >>$FILETO <<EOF

Пакеты PostgreSQL для системы ${TEXTDIST} (файлы postgresql*):
EOF

	LOCALFILES=`find -L $PGLOCAL/$DIST -maxdepth 1 -type f`
	printURL $PGLOCAL/$DIST $PGDOWNLOAD1/$DIST $LOCALFILES >>$FILETO || fatal "Error with mirror 1 ($PGLOCAL with '$LOCALFILES') (possible files are missed!)"


	cat >>$FILETO <<EOF

Документация и краткая инструкция по установке доступна по адресу
http://wiki.etersoft.ru/SELTA

По вопросам использования продукта пишите на selta@etersoft.ru, указав
в теме письма регистрационный номер.

Пожалуйста, отвечайте на это письмо только
при возникновении затруднений со скачиванием файлов.

$THANKTEXT

-- 
Команда разработчиков
Etersoft, 2023
EOF
}

build_selta_license()
{
	PROJECTNAME="SELTA@Etersoft"
	VERNAME=$PROJECTNAME/$PROJECTVERSION
	TARGETDIR=/var/ftp/pub/download/SELTA@Etersoft/$TARGETDIRNAME
	DOWNLOADDIR="$MPROTO://$DOWNLOADDOMAIN/pub/download/SELTA@Etersoft/$TARGETDIRNAME"

	# exports FTPDIR
	LICENSEFILE=selta.lic
	LICENSEDIR="C:\\Program Files\\Selta"
	create_license_dir

	# Для отправки писем обязательно нужна локаль!
	export LC_ALL=ru_RU.UTF-8
	TMPMAIL=$(make_temp_file)
	prepare_license_mail $TMPMAIL selta@etersoft.ru || fatal "Can't prepare letter"
	cat $TMPMAIL | mutt "${FULLMAILTO}" -b "sales-track@etersoft.ru" -s "$ETERREGNUM: Лицензия для продукта $COMPONENTNAME" || fatal "Can't send"
	rm -f $TMPMAIL
	rm -f $TMPDIR/selta.lic
}

build_selta()
{
	PROJECTNAME="SELTA@Etersoft"
	VERNAME=$PROJECTNAME/$PROJECTVERSION

	if [ -n "$LICENSEONLY" ] ; then
		build_selta_license
		return
	fi

	# SELTA@Etersoft
	PUBLOCAL="/var/ftp/pub/Etersoft/$VERNAME/Windows"
	PUBDOWNLOAD1="$MPROTO://$DOWNLOADDOMAIN/pub/Etersoft/$VERNAME/Windows"

	# Postgre@Etersoft
	PGLOCAL="/var/ftp/pub/Etersoft/$VERNAME/Postgre"

	# Use real path instead link
	if [ -L "$PGLOCAL" ] ; then
		PGLOCAL=`readlink -f "$PGLOCAL"`
	fi
	PGDOWNLOAD1="$MPROTO://$DOWNLOADDOMAIN/$(echo $PGLOCAL | sed -e "s|/var/ftp/||g")"

	# Target dir
	TARGETDIR=/var/ftp/pub/download/SELTA@Etersoft/$TARGETDIRNAME
	DOWNLOADDIR="$MPROTO://$DOWNLOADDOMAIN/pub/download/SELTA@Etersoft/$TARGETDIRNAME"


	TEXTDIST=$DIST
	# Check for linked system (собираем для основной системы)
	if [ -L "$PGLOCAL/$DIST" ] ; then
		DIST=`readlink $PGLOCAL/$DIST | sed -e "s|\.\./||g"`
		TEXTDIST="$TEXTDIST (фактически сборка выполнена для $DIST)"
	fi

	check_dist $DIST
	REBUILDLIST=$DIST
	echo "Work with $TASK for $REBUILDLIST"

	CHECKCOMP=postgre-etersoft9.2
	check_and_refresh_component bin-postgres $PGLOCAL $CHECKCOMP
	assert_present_package $PGLOCAL/$DIST $CHECKCOMP

	# exports FTPDIR
	LICENSEFILE=selta.lic
	LICENSEDIR="C:\\Program Files\\Selta"
	create_license_dir

	# Для отправки писем обязательно нужна локаль!
	export LC_ALL=ru_RU.UTF-8
	TMPMAIL=`mktemp`
	prepareSeltaMail $TMPMAIL || fatal "Can't prepare letter"
	cat $TMPMAIL | mutt "${FULLMAILTO}" -b "sales-track@etersoft.ru" -s "$ETERREGNUM: Сборка $COMPONENTNAME" || fatal "Can't send"
	rm -f $TMPMAIL
}

