#!/bin/sh -x
##
#  Korinf project
#
#  Publish SELTA@Etersoft product for client by task file
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2006, 2007, 2009
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2006, 2007, 2009
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

# Выполняет сборку по первому заказу в списке
# Отправляет на реальный адрес только с параметром --real /путь
# Также отладку можно включить, создав файл arobot.sh.debug
# (c) Etersoft
# 08.06.2006, 09.06.06, 28.02.07, 09.03.07, 15.12.07, 2008
# FIXME: если в имени запятая, разделяет на два адреса
#


# Ошибка: не ловятся ошибки отсюда
prepareSeltaMail()
{
	local FILETO BETA
	FILETO=$1
	>$FILETO
	NAME=`get_name "$FULLNAME"`
	BETA=""
	cat >>$FILETO <<EOF
${DEAR} ${NAME}!

Ваш заказ Продукта ${PRODUCT} (релиз $PROJECTVERSION) выполнен.
${BETA}
Регистрационный номер Продукта: ${ETERREGNUM}.

Для получения Продукта необходимо скачать файлы по приведённым ссылкам:

Установочный пакет SELTA@Etersoft (файл selta.msi) и файл лицензии (selta.lic):
EOF
	LOCALFILES=selta.msi
	printURL $PUBLOCAL $PUBDOWNLOAD1 $LOCALFILES >>$FILETO || fatal "Error with mirror 1 ($PUBLOCAL with '$LOCALFILES') (possible files are missed!)"
	printURL $FTPDIR $DOWNLOADDIR/$PROJECTVERSION `find -L  $FTPDIR -maxdepth 1 -type f ` >>$FILETO || fatal "Error with private part (files are missed) "

	cat >>$FILETO <<EOF

Пакеты PostgreSQL для системы ${TEXTDIST} (файлы postgresql*):
EOF

	LOCALFILES=`find -L $PGLOCAL/$DIST -maxdepth 1 -type f`
	printURL $PGLOCAL/$DIST $PGDOWNLOAD1/$DIST $LOCALFILES >>$FILETO || fatal "Error with mirror 1 ($PGLOCAL with '$LOCALFILES') (possible files are missed!)"


	cat >>$FILETO <<EOF

Документация и краткая инструкция по установке доступна по адресу
http://wiki.etersoft.ru/SELTA

При необходимости эти же файлы могут быть получены через http: замените ftp:// на http:// в пути.

Скачать сборки PostgreSQL под другие системы можно здесь:
	$PGDOWNLOAD1

При возникновении затруднений со скачиванием файлов просим привести
описание проблемы в ответе на данное письмо.

Благодарим Вас за покупку!
-- 
Команда разработчиков
Etersoft, 2009
EOF
}

build_selta()
{
	PROJECTNAME="SELTA@Etersoft"
	VERNAME=$PROJECTNAME/$PROJECTVERSION
	
	PUBLOCAL="/var/ftp/pub/Etersoft/$VERNAME/Windows"
	PUBDOWNLOAD1="ftp://updates.etersoft.ru/pub/Etersoft/$VERNAME/Windows"

	if [ "$PROJECTVERSION" = "1.0.5" ] ; then
		PGVERSION="8.2"
	else
		PGVERSION="8.3"
	fi
	PGLOCAL="/var/ftp/pub/Etersoft/PostgreSQL/$PGVERSION"
	PGDOWNLOAD1="ftp://updates.etersoft.ru/pub/Etersoft/PostgreSQL/$PGVERSION"

	TARGETDIR=/var/ftp/pub/download/SELTA@Etersoft/$TARGETDIRNAME
	DOWNLOADDIR="http://updates.etersoft.ru/pub/download/SELTA@Etersoft/$TARGETDIRNAME"

	
	if [ ! -d "$PGLOCAL/$DIST" ] ; then
		warning "System $DIST not supported for build ($PGLOCAL/$DIST does not exist)"
		do_broken
	fi
	
	TEXTDIST=$DIST
	# Check for linked system (собираем для основной системы)
	if [ -L "$PGLOCAL/$DIST" ] ; then
		DIST=`readlink $PGLOCAL/$DIST | sed -e "s|\.\./||g"`
		TEXTDIST="$TEXTDIST (фактически сборка выполнена для $DIST)"
	fi
	
	check_dist $DIST
	REBUILDLIST=$DIST
	echo "Work with $TASK for $REBUILDLIST"

	export FTPDIR=$TARGETDIR/$PROJECTVERSION
	# Можем стирать только каталог дистрибутива, а не весь
	test -d $FTPDIR && rm -rf $FTPDIR
	mkdir -p $FTPDIR || fatal "error with $FTPDIR creating"

	export ETERREGNUM
	echo >> $ALOGDIR/autobuild.report.log
	echo "Build $TYPE for $ETERREGNUM in $FTPDIR" >> $ALOGDIR/autobuild.report.log

	# Вывод скрипта не записывается в лог
	export BUILDSTRAP=
	#
	if [ "$PROJECTVERSION" = "1.0.5" ] ; then
		create_compat_license $FTPDIR/selta.lic $AROBOTDIR/dsa/selta.dsa
	else
		create_license $FTPDIR/selta.lic $AROBOTDIR/dsa/selta.dsa
	fi

	# Для отправки писем обязательно нужна локаль!
	export LC_ALL=ru_RU.UTF-8
	TMPMAIL=`mktemp`
	prepareSeltaMail $TMPMAIL || fatal "Can't prepare letter"
	cat $TMPMAIL | mutt "${FULLMAILTO}" -b "wine@etersoft.ru" -s "Сборка $PRODUCT" || fatal "Can't send"
	rm -f $TMPMAIL
}

