#!/bin/sh -x
##
#  Korinf project
#
#  Publish WINE@Etersoft product for client by task file
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2006, 2007, 2009
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2006, 2007, 2009
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##



# Ошибка: не ловятся ошибки отсюда
prepare_wine_etersoft_mail_html()
{
	local FILETO BETA HTMLTO=$FTPDIR/download.html
	FILETO=$1
	>$FILETO
	>$HTMLTO
	NAME="$(get_dear_from_fio "$FULLNAME" "покупатель")"
	BETA=""
	# FIXME: is it used?
	if [ "$RELEASECANDIDAT" = "1" ] ; then
		BETA="
		<p class="comment_warning" align="center">Это бета-версия продукта, используйте её с осторожностью!
<br>Устанавливайте в повседневное использование только после тестирования!
<br>Создавайте резервные копии чаще!</p>
"
	fi

CIFSTEXT=""
if [ "$TYPE" != "Local" ] ; then
fatal "Нужно переписать!!!"
CIFSTEXT="
Для обеспечения взаимодействия по протоколу CIFS с сервером
SAMBA или Windows Server - пакет с модулем ядра Linux CIFS:
	$PUBDOWNLOAD1CIFS
"
fi

if [ "$TYPE_LICENSE" = "Demo" ] || [ "$TYPE_LICENSE" = "DemoTerminal" ] ; then
	THANKTEXT="Благодарим Вас за внимание к нашему продукту."
else
	THANKTEXT="Благодарим Вас за покупку!"
fi

	cat >>$FILETO <<EOF
${DEAR} ${NAME}!

Ваш заказ по сборке Продукта ${PRODUCT} (релиз $PROJECTVERSION)
для системы ${TEXTDIST} выполнен.
Регистрационный номер Продукта: ${ETERREGNUM}.

Ссылки для скачивания файлов Продукта находятся здесь:
${DOWNLOADDIR}/$TYPE-$PROJECTVERSION/$DIST/download.html

По вопросам использования продукта пишите на support@etersoft.ru, указав
в ТЕМЕ (Subject) письма регистрационный номер.

Пожалуйста, отвечайте на это письмо только
при возникновении затруднений со скачиванием файлов.

$THANKTEXT
-- 
Команда разработчиков
Etersoft, 2010
EOF

cat >>$HTMLTO <<EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
 <title>Сссылки для получения продукта ${PRODUCT}</title>
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>

<style type="text/css">
  comment_warning {
    background-color: #FF0000;
    color:Black;
    font-size:12px;
    padding:10px;
  };
  comment_note {
    background-color: #FFFF00;
    color:Black;
    font-size:12px;
    padding:10px;
  };
</style>

<body>
<center>
<table border="0" cellspacing="0" cellpadding="0" width="770">
<tr>
	<td valign="middle"><span class="title">Etersoft - привычные программы на свободной платформе</span></td>
	<td valign="bottom" align="right"><br /><span class="date">Вторник, 07 Июль 2009 &nbsp;</span></td>
</tr>
</table>

<table border="0" cellspacing="0" cellpadding="0" width="774">
	<tr><td bgcolor="#333333" colspan="3">
	</tr>

<h2>Получение продукта ${PRODUCT}</h2>
<p>
${DEAR} ${NAME}!

Сборка Продукта ${PRODUCT} (релиз $PROJECTVERSION) для системы ${TEXTDIST}.
${BETA}
Регистрационный номер Продукта: ${ETERREGNUM}.

Для получения Продукта необходимо скачать файлы по приведённым ссылкам, в их числе:
<ul>
 <li>пакеты Продукта (wine-etersoft, wine-etersoft-$PRODUCT_name)</li>
 <li>файл лицензии WINE-ETERSOFT.LIC</li>
 <li>документацию (файл manual.html)</li>
 <li>пакет драйверами аппаратных ключей защиты HASP 4/HL/SRM, Smartkey 3 Eutron и SafeNet Sentinel (hasp);</li>
 <li>пакет со свободными шрифтами Liberation (fonts-ttf-liberation). Во многих дистрибутивах он уже есть (в Ubuntu называется ttf-liberation).</li>
</ul>

Ссылки для скачивания файлов вашего экземпляра Продукта по протоколу FTP:
	$(printHTMLURL "$FTPDIR" "$DOWNLOADDIR/$TYPE-$PROJECTVERSION/$DIST" `find -L $FTPDIR -maxdepth 1 -type f | sort` >>$FILETO || fatal "Error with files (files are missed) ")
<br>(действительны в течение 4 суток)

Ссылки для скачивания файлов вашего экземпляра Продукта по протоколу HTTP:
	$(printHTMLURL "$FTPDIR" "${DOWNLOADDIR/ftp/http}/$TYPE-$PROJECTVERSION/$DIST" `find -L $FTPDIR -maxdepth 1 -type f | sort` >>$FILETO || fatal "Error with files (files are missed) ")
<br>(действительны в течение 4 суток)

<p style="comment_note">
ОБРАТИТЕ ВНИМАНИЕ!
Файл лицензии <a href=$(printHTMLURL "$FTPDIR" "$DOWNLOADDIR/$TYPE-$PROJECTVERSION/$DIST" $FTPDIR/WINE-ETERSOFT.LIC >>$FILETO || fatal "Error with WINE-ETERSOFT.LIC ")>WINE-ETERSOFT.LIC</a> необходимо расположить в каталоге /etc/wine, ~/.wine или C:\WINDOWS\INF.
</p>

$CIFSTEXT

Для полного соответствия шрифтов в программах можно <a href=$PUBDOWNLOAD1FONTS>скачать</a> и установить <a href=$PUBDOWNLOAD1FONTS>пакет fonts-ttf-ms</a>,
содержащий шрифты MS Core Fonts.

Также Вы можете напрямую <a href=$DOWNLOADDIR/$TYPE-$PROJECTVERSION/$DIST>зайти в каталог</a>, чтобы загрузить файлы открытой и закрытой части.

Обязательно ознакомьтесь с известными проблемами в текущей сборке:
http://wiki.etersoft.ru/WINE/knownbugs

Ответы на частые вопросы смотрите на <a href=http://etersoft.ru/wine/faq>http://etersoft.ru/wine/faq</a>.

По вопросам использования продукта пишите <a href="mailto:support@etersoft.ru">в службу поддержки</a>, указав
в ТЕМЕ (Subject) письма регистрационный номер ${ETERREGNUM}.

$THANKTEXT
<br>
<i>Команда разработчиков Etersoft, 2010</i>

</table>
</body>
</html>
EOF
}

