#!/bin/bash
##
#  Korinf project
#
#  Send message by jabber functions
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2010
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2010
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##


# -s "Subject", e-mail, message in stdout
send_by_jabber()
{
        local SUBJECT MESSAGE
        if [ "$1" = "-s" ] ; then
                SUBJECT="$2"
                shift 2
        fi
        MESSAGE="$(cat)"
        export KORINFERJID KORINFERJIDPASSWD
        for recv in $@ ; do
                # python program
                $KORINFDIR/korinf/helpers/send_via_pyxmpp.py "$recv" "$SUBJECT" "$MESSAGE"
        done
}
