#!/bin/sh -x
##
#  Korinf project
#
#  Publish product functions
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2006, 2007, 2009, 2013
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2006, 2007, 2009, 2013
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

# arg: src.rpm target_file
# Check if target is older then src.rpm and build if needed

# is not recommended include directly due message function intersection
#kormod korinf

kormod check_integrity status

# uses DIST FORCEBUILD
# changes DESTDIR
check_if_updated()
{
	assert_var DIST
	local BUILDNAME="$1"
	local SOURCEPATH="$2"
	local PRODPATH="$3"
	local BINBUILDNAME="$4"
	[ -n "$BINBUILDNAME" ] || BINBUILDNAME="$BUILDNAME"
	
	# FIXMEP get_..._package always returns true
	local SRCRPM=$(get_src_package "$SOURCEPATH" $BUILDNAME)
	test -r "$SRCRPM" || fatal "Source package for $BUILDNAME is not found"
	local BINPKG=$(get_bin_package "$PRODPATH/$DIST" $BINBUILDNAME)

	# if binary is exists
	if [ -r "$BINPKG" ] ; then
		# if binary is newer than src.rpm
		if [ "$BINPKG" -nt "$SRCRPM" ] ; then
			check_pkg_integrity "$BINPKG" && return 0

			# TODO: используется неизвестное метод сжатия для «control.tar.zst», прекращаем
			# В Ubuntu напрочь другая ветка dpkg, где поддерживается zstd: https://launchpad.net/ubuntu/+source/dpkg/1.20.9ubuntu2
			# Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664
			rhas $DIST "Ubuntu/22.04" && return 0
			# epm checkpkg: sha1 ?UnknownSigatureType? md5 НЕ ОК
			rhas $DIST "ROSA/2021.1" && return 0
			# epm checkpkg: sha1 ?UnknownSigatureType? md5 НЕ ОК
			rhas $DIST "RockyLinux/8" && return 0
			# epm checkpkg: sha1 ?UnknownSigatureType? md5 НЕ ОК
			rhas $DIST "Fedora" && return 0

			fatal "Package $BINPKG is broken!!! Check it with epm checkpkg"
			# We can't remove files partially
			#rm -vf "$BINPKG"
		fi
	fi

	# used for autobuild_failed
	DESTDIR=$PRODPATH/$DIST

	#if [ -z "$FORCEBUILD" ] ; then
	is_autobuild_failed && fatal "Package $BINBUILDNAME should be rebuilt from $SRCRPM, but previous autobuild was failed"
	#fi

	return 1
}

# Args: BUILDSCRIPTDIR   PRODPATH                     BUILDNAME  [PRVERSION]
# Example: bin-etercifs  /var/.../WINE@Etersoft/CIFS  etercifs   5.4.7
check_and_refresh_component()
{
	assert_var DIST
	local BUILDSCRIPTDIR="$1"
	# Etersoft/RX@Etersoft/last
	local PRODPATH="$2"
	# Etersoft/RX@Etersoft/last/sources
	local SOURCEPATH="$(get_sources_dir "$PRODPATH")"
	# haspd
	local BUILDNAME=$3
	local PRVERSION=$4
	local BINBUILDNAME=$5
	[ -n "$BINBUILDNAME" ] || BINBUILDNAME=$BUILDNAME

	check_if_updated $BUILDNAME $SOURCEPATH $PRODPATH $BINBUILDNAME && return 0

        # FIXME: hack
        if [ -z "$PRVERSION" ] ; then
               # get PROJECT version from SOURCEPATH
               PRVERSION=$(basename $(dirname $SOURCEPATH) )
        fi

	if [ -x $AROBOTDIR/../$BUILDSCRIPTDIR/$BINBUILDNAME.sh ] ; then
		$AROBOTDIR/../$BUILDSCRIPTDIR/$BINBUILDNAME.sh -f $DIST $PRVERSION && return 0
	else
		$AROBOTDIR/../$BUILDSCRIPTDIR/$BUILDNAME.sh -f $DIST $PRVERSION && return 0
	fi

	set_autobuild_failed
	fatal "Can't rebuild $BINBUILDNAME package"
	return 1
}

# Args: PRODPATH BUILDNAME
# Example: /var/ftp/pub/Korinf eepm
check_and_refresh_package()
{
	assert_var DIST
	# Etersoft/RX@Etersoft/last
	local PRODPATH=$1
	# Etersoft/RX@Etersoft/last/sources
	local SOURCEPATH="$(get_sources_dir "$PRODPATH")"
	local BUILDNAME=$2
	local BINBUILDNAME=$3
	[ -n "$BINBUILDNAME" ] || BINBUILDNAME=$BUILDNAME

	check_if_updated $BUILDNAME $SOURCEPATH $PRODPATH $BINBUILDNAME && return 0

	$AROBOTDIR/../bin/korinf -f $BUILDNAME $DIST $PRODPATH && return 0

	set_autobuild_failed
	fatal "Can't rebuild $BINBUILDNAME package"
	return 1
}
