#!/bin/sh -x
##
#  Korinf project
#
#  Publish product functions
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2006, 2007, 2009
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2006, 2007, 2009
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

get_product_type()
{
	local TYPE
	local PRODUCT="$1"
	case "$PRODUCT" in
		*Network\ Lite*)
			TYPE="NetworkLite"
			;;
		*Network*)
			TYPE="Network"
			;;
		*Local*)
			TYPE="Local"
			;;
		*SQL*)
			TYPE="SQL"
			;;
		*CAD*)
			TYPE="CAD"
			;;
		*School*)
			TYPE="School"
			;;
		*PREMIUM*)
			TYPE="PREMIUM"
			;;
		*Enterprise*)
			TYPE="Network"
			;;
		*)
			fatal "Unknown product $PRODUCT"
			;;
	esac
	echo $TYPE
}

DOWNLOADDOMAIN=download.etersoft.ru
