#!/bin/sh -x
##
#  Korinf project
#
#  Publish product functions
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2006, 2007, 2009
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2006, 2007, 2009
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

GENERATE_SIG=$AROBOTDIR/dsa/generate_sig

# Create license from variables
# args: filename, dsakey
create_license()
{
	local LICENSE_FILE="$1"
	local DSAKEY="$2"
	test -r "$DSAKEY" || fatal "Private DSA key $DSAKEY is missed"

	# Check all license fields
	[ -n "$PROJECTVERSION" ] || fatal "PROJECTVERSION is empty"
	[ -n "$PRODUCT" ] || fatal "PRODUCT is empty"
	[ -n "$ETERREGNUM" ] || fatal "ETERREGNUM (LICENSE_NUMBER) is empty"
	[ -n "$OWNER" ] || fatal "OWNER is empty"
	#[ -n "$FULLNAME" || fatal "RESPONSIBLE is empty"
	[ -n "$TYPE_LICENSE" ] || fatal "TYPE_LICENSE is empty"
	[ -n "$DATE_START" ] || fatal "DATE_START is empty"
	[ -n "$DATE_END" ] || fatal "DATE_END is empty"

	rm -f "$LICENSE_FILE.tmp" "$LICENSE_FILE"
LC_ALL=ru_RU.UTF-8 cat <<EOF >"$LICENSE_FILE.tmp"
VERSION=$PROJECTVERSION
PRODUCT=$PRODUCT
LICENSE_NUMBER=$ETERREGNUM
OWNER=$OWNER
RESPONSIBLE=$FULLNAME
TIMESTAMP=$(date)
TYPE_LICENSE=$TYPE_LICENSE
NAME_LICENSE=$NAME_LICENSE
DATE_START=$DATE_START
DATE_END=$DATE_END
EOF

if [ -n "$COUNT_LICENSE" ] && [ ! "$COUNT_LICENSE" = "0" ] ; then
	#echo "# Количество компьютеров" >> "$LICENSE_FILE.tmp"
	echo "COUNT_LICENSE=$COUNT_LICENSE" >> "$LICENSE_FILE.tmp"
fi

	echo "Create license for $PROJECTVERSION with $ETERREGNUM"
	LC_ALL=ru_RU.UTF-8 $GENERATE_SIG "$LICENSE_FILE.tmp" "$DSAKEY" "$LICENSE_FILE" | iconv -f koi8-r -r
	test -r "$LICENSE_FILE" || fatal "Can't sign license file"
	rm -f "$LICENSE_FILE.tmp"
}

create_compat_license()
{
	local DEST="$1"
	# Подпись
	unset DISPLAY
	# Ключ в private_key.dsa
	cd /home/builder/Projects/eterbuild/sig
	LICENSE_FILE=selta.lic
	test -r $LICENSE_FILE && fatal "Some license file already exists"
#TYPE_LICENSE=Corporate
cat <<EOF >$LICENSE_FILE
VERSION=$PROJECTVERSION
LICENSE_NUMBER=$ETERREGNUM
OWNER=$OWNER
RESPONSIBLE=$FULLNAME
TYPE_LICENSE=$TYPE_LICENSE
DATE_START=$DATE_START
DATE_END=$DATE_END
EOF
	rm -f $LICENSE_FILE.sig
	wine generate_sig.exe $LICENSE_FILE
	rm -f $LICENSE_FILE
	test -r $LICENSE_FILE.sig || fatal "Can't sign license file"
	mv -f $LICENSE_FILE.sig $DEST || fatal "Can't move license file to $DEST"
	cd -
}
