#!/bin/sh -x
##
#  Korinf project
#
#  Publish product functions
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2006, 2007, 2009
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2006, 2007, 2009
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##


send_webusy()
{
	export LC_ALL=ru_RU.UTF-8

# Письмо клиенту

NAME="$(get_dear_from_fio "$FULLNAME" "покупатель")"

export EMAIL="Система отгрузки Etersoft <support@etersoft.ru>"
(	echo "
${DEAR} ${NAME}!

Вы заказали сборку продукта ${PRODUCT} (релиз $PROJECTVERSION)
для системы ${DIST}.

К сожалению, в настоящий момент по причине подготовки
новой версии программы ваш заказ выполнить невозможно.

Ваш заказ принят и будет обработан после возобновления
работы системы отгрузки.
Повторно заказывать получение экземпляра не нужно.

Надеемся на понимание и приносим извинения за задержку.

-- 
КОМАНДА РАЗРАБОТЧИКОВ
Etersoft, 2013
" ;
) | mutt -s "Сборка ${PRODUCT} задерживается" "${FULLMAILTO}" -b "support@etersoft.ru"

}

send_fatal()
{
	export LC_ALL=ru_RU.UTF-8
	if [ -z "$TASK" ] ; then
		return 1
	fi
	[ -z "$TMPMAIL" ] && TMPMAIL=/dev/null

# Письмо в support
(	echo "
Произошла ошибка '${@}' при сборке
продукта $PRODUCT (релиз $PROJECTVERSION) с номером $ETERREGNUM
для платформы $DIST. Получатель: $FULLMAILTO.
Каталог результата: $TARGETDIR.
Задание отложено до исправления проблемы.

Prepared mail in $TMPMAIL:
`cat $TMPMAIL`

-- 
Робот сборки Korinf v.2.0.1
Etersoft, 2013
" ;
[ -r "$LOGFILE" ] && echo "Лог сборки $LOGFILE приложен." || echo "Лог сборки $LOGFILE не был создан. "
) | mutt -s "Ошибка при сборке $ETERREGNUM  на ${DIST}" $EMAILNOTIFY $PARAMMUTT

# Письмо клиенту
NAME="$(get_dear_from_fio "$FULLNAME")"

export EMAIL="Система отгрузки Etersoft <support@etersoft.ru>"
if tail -n1 $TASK | grep -v FAILED ; then
(	echo "
${DEAR} ${NAME}!

Вы заказали сборку продукта ${PRODUCT} (релиз $PROJECTVERSION)
для системы ${DIST}.

К сожалению, в нашей системе отгрузки произошла ошибка при сборке пакета для Вас.
Мы просим Вас подождать, пока мы её исправим.
Пожалуйста, только в случае крайней необходимости пишите об этой проблеме в службу поддержки.
Не сообщайте о проблеме в систему отслеживания ошибок.
Не звоните в офис компании, секретарь вам не сможет помочь.
Мы уже и так работаем над исправлением проблемы. Возможно это потребует некоторого времени.
Но ВАШ ЗАКАЗ ПРИНЯТ и будет обработан.
Повторно заказывать получение экземпляра не нужно, это не поможет.
Надеемся на понимание и приносим извинения за задержку.

-- 
Команда разработчиков
Etersoft, 2013
" ;
) | mutt -s "Ошибка при сборке ${ETERREGNUM} на ${DIST}" "${FULLMAILTO}" -b "support@etersoft.ru"
fi
	return 0
}

