#!/bin/sh -x
##
#  Korinf project
#
#  Publish product functions
#
#  Copyright (c) Etersoft <http://etersoft.ru> 2006, 2007, 2009
#  Copyright (c) Vitaly Lipatov <lav@etersoft.ru> 2006, 2007, 2009
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

. $AROBOTDIR/funcs/mail

warning()
{
	test -n "$@" && echo "Warning: $@"
}


fatal()
{
	LOGFILE=$ALOGDIR/$DIST/$BUILDNAME.log
	[ -r "$LOGFILE" ] && PARAMMUTT="-a $LOGFILE" || PARAMMUTT=""

	echo "$@" >&2

	send_fatal "$@" || exit_now 1

	DATE=`date`
	echo "# built FAILED at $DATE (Error: ${@})" >>$TASK
	[ -e "$TASK" ] && mv -f $TASK $TASK.failed
	exit_now 1
}

