#!/bin/sh

. ./config

set_module()
{
local ver="$1"
case $ver in
    1.4*)
        ver=1
        ;;
    1.5*)
        ver=2
        ;;
esac
export KORINFMODULE=rx
}


set_ver()
{
    # System/Version [Version] [option]
    ver="$3"
    case "$ver" in
        -*|"")
            ver="$2"
            ;;
    esac

    case "$ver" in
        -*)
            ver=""
            ;;
    esac

    [ -n "$ver" ]|| ver="$DEFAULTVERSION"
    set_module "$ver"
}
